apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clinic-api-ingress
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: clinic-api-service
                port:
                  number: 80
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: clinic-api-service
                port:
                  number: 80
